# Supabase CLI configuration file
# Learn more about this file here: https://supabase.com/docs/guides/cli/config

[project]
# Project ID: set by `supabase init` and `supabase link`
id = "your-project-id"

[features]
# Enable or disable the dashboard.
dashboard = true

[studio]
# Studio port
port = 8000

[inbucket]
# Inbucket port
port = 54325

[db]
# Database URL (used by `supabase db diff` and `supabase migration up`)
# If you are using a remote database, you can set this to your database connection string.
# If you are using a local database, you can use the default value.
# Example: `postgresql://postgres:postgres@localhost:5432/postgres`
# If you are using a self-hosted database, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a managed database, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
# Example: `postgresql://postgres:password@localhost:5432/database_name`
# If you are using a database from a cloud provider, you can set this to your database connection string.
