# Supabase CLI configuration file
# Learn more about this file here: https://supabase.com/docs/guides/cli/config

[project]
# Project ID from Supabase Dashboard
# e.g. 'aaaaaaaaaaaaaaaaaaaa'
id = ""

[db]
# The database URL to connect to when running commands.
# Can be overridden with the --db-url flag.
# If not set, the CLI will use the URL from `supabase link` or `supabase init`.
# url = "postgresql://postgres:password@localhost:54322/postgres"

# The path to the migrations folder.
migrations_path = "supabase/migrations"

# The name of the database schema to use for the migrations.
# This is useful if you are using a custom schema for your database.
# schema = "public"

# The name of the database role to use for the migrations.
# This is useful if you are using a custom role for your database.
# role = "postgres"

# The maximum number of seconds to wait for a database connection.
# connection_timeout = 5

# The maximum number of retries for a database connection.
# connection_retries = 3

# The path to the file that contains the database seed data.
# seed_path = "supabase/seed.sql"

[functions]
# The path to the functions folder.
# path = "supabase/functions"

[storage]
# The path to the storage folder.
# path = "supabase/storage"

[realtime]
# The path to the realtime folder.
# path = "supabase/realtime"

[graphql]
# The path to the GraphQL folder.
# path = "supabase/graphql"

[studio]
# The port to use for the Supabase Studio.
# port = 54323

[inbucket]
# The port to use for the Inbucket email server.
# port = 54324

[gotrue]
# The port to use for the GoTrue authentication server.
# port = 9999

[api]
# The port to use for the API server.
# port = 8000

[diff]
# The path to the diff tool to use.
# tool = "diff"

[logs]
# The path to the logs folder.
# path = "supabase/logs"

[telemetry]
# Whether to enable telemetry.
# enabled = true
