[project]
name = "inclulearnglobal"
db_name = "postgres"
db_user = "postgres"
db_password = ""
db_host = "localhost"
db_port = 5432
db_url = ""
db_schema = "public"
db_migrations_path = "supabase/migrations"
db_seed_path = "supabase/seed.sql"
db_anon_role = "anon"
db_authenticated_role = "authenticated"
db_service_role = "service_role"
db_jwt_secret = ""
db_jwt_expiry = 3600
db_max_rows = 1000
db_pool_size = 10
db_connection_timeout = 5
db_statement_timeout = 5000
db_idle_timeout = 10
db_log_level = "info"
db_enable_ddl_commands = true
db_enable_foreign_data_wrappers = false
db_enable_http_functions = false
db_enable_pg_net = false
db_enable_pg_cron = false
db_enable_pg_graphql = false
db_enable_pg_stat_statements = false
db_enable_pg_trgm = false
db_enable_pg_vector = true
db_enable_postgis = false
db_enable_timescaledb = false
db_enable_vault = false
db_enable_wrappers = false
db_enable_extensions = ["uuid-ossp", "vector"]

[studio]
port = 8000
host = "localhost"
log_level = "info"

[inbucket]
port = 5433
host = "localhost"
log_level = "info"

[graphql]
port = 5434
host = "localhost"
log_level = "info"

[realtime]
port = 5435
host = "localhost"
log_level = "info"

[storage]
port = 5436
host = "localhost"
log_level = "info"

[auth]
port = 5437
host = "localhost"
log_level = "info"

[functions]
port = 5438
host = "localhost"
log_level = "info"

[meta]
version = "1.0.0"
