-- This is a migration file. Its content should be managed by Supabase CLI.
-- It's typically a timestamped file for schema changes.
-- Example content:
-- create table public.user_preferences (
--   id uuid primary key references auth.users on delete cascade,
--   preferred_flow text,
--   notification_settings jsonb,
--   created_at timestamp with time zone default now()
-- );
