-- This is a migration file. Its content should be managed by Supabase CLI.
-- It's typically a timestamped file for schema changes.
-- Example content:
-- create table public.search_history (
--   id uuid primary key default uuid_generate_v4(),
--   user_id uuid references auth.users on delete cascade,
--   query text not null,
--   search_type text,
--   searched_at timestamp with time zone default now()
-- );
