-- Insert sample schools data
INSERT INTO schools (name, location, description, specialties, fees, rating, age_range, contact_email, contact_phone, accessibility_features, therapy_services) VALUES
('Sunshine Special School', 'Nairobi', 'Premier inclusive education with specialized therapy programs and individualized learning plans', ARRAY['Autism', 'ADHD', 'Learning Disabilities'], 'KSh 85,000/term', 4.8, '3-18 years', 'info@sunshinespecial.co.ke', '+254 711 123456', ARRAY['Wheelchair accessible', 'Sensory rooms', 'Adaptive technology'], ARRAY['Speech therapy', 'Occupational therapy', 'Behavioral therapy']),
('Hope Valley Academy', 'Mombasa', 'Innovative learning approaches for children with diverse needs and comprehensive support services', ARRAY['Dyslexia', 'Learning Disabilities', 'ADHD'], 'KSh 65,000/term', 4.6, '5-16 years', 'admissions@hopevalley.co.ke', '+254 722 234567', ARRAY['Visual aids', 'Hearing loops', 'Modified equipment'], ARRAY['Educational therapy', 'Psychological support']),
('Rainbow Bridge School', 'Kisumu', 'Fully accessible campus with expert physiotherapy support and inclusive environment', ARRAY['Cerebral Palsy', 'Physical Disabilities', 'Multiple Disabilities'], 'KSh 75,000/term', 4.7, '4-17 years', 'contact@rainbowbridge.co.ke', '+254 733 345678', ARRAY['Wheelchair accessible', 'Physiotherapy equipment', 'Adaptive sports'], ARRAY['Physical therapy', 'Occupational therapy', 'Speech therapy']),
('Bright Minds Academy', 'Nakuru', 'Specialized education for gifted children with learning differences', ARRAY['Autism', 'Giftedness', 'Twice Exceptional'], 'KSh 95,000/term', 4.9, '6-18 years', 'info@brightminds.co.ke', '+254 744 456789', ARRAY['Sensory-friendly', 'Technology integration'], ARRAY['Cognitive behavioral therapy', 'Social skills training']),
('Unity Special School', 'Eldoret', 'Community-focused education with strong family involvement programs', ARRAY['Down Syndrome', 'Intellectual Disabilities', 'Autism'], 'KSh 55,000/term', 4.5, '3-16 years', 'unity@specialeducation.co.ke', '+254 755 567890', ARRAY['Family support center', 'Community integration'], ARRAY['Life skills training', 'Vocational therapy']);

-- Insert sample outdoor clubs data
INSERT INTO outdoor_clubs (name, location, description, activities, age_range, rating, accessibility_features, contact_email, contact_phone, meeting_schedule, fees) VALUES
('Nature Explorers Club', 'Nairobi - Central Park', 'Weekly nature walks and hands-on science activities for children with special needs', ARRAY['Nature walks', 'Science experiments', 'Wildlife observation'], '6-12 years', 4.8, ARRAY['Wheelchair-accessible trails', 'Sensory-friendly activities'], 'info@natureexplorers.co.ke', '+254 766 678901', 'Saturdays 9AM-12PM', 'KSh 2,000/month'),
('Young Artists Collective', 'Mombasa - Community Arts Center', 'Creative workshops combining visual arts and theater for inclusive expression', ARRAY['Painting', 'Drama', 'Sculpture', 'Music'], '5-15 years', 4.9, ARRAY['Autism-friendly environment', 'Visual aids', 'Adaptive tools'], 'contact@youngartists.co.ke', '+254 777 789012', 'Wednesdays & Saturdays 2PM-5PM', 'KSh 3,500/month'),
('Little Athletes Club', 'Kisumu - Sports Complex', 'Inclusive sports program focused on fun and skill development', ARRAY['Adapted sports', 'Swimming', 'Track and field'], '4-10 years', 4.7, ARRAY['Modified equipment', 'Trained coaches', 'Medical support'], 'sports@littleathletes.co.ke', '+254 788 890123', 'Tuesdays & Thursdays 4PM-6PM', 'KSh 4,000/month'),
('Adventure Scouts', 'Nakuru - Outdoor Center', 'Outdoor adventures and camping experiences adapted for special needs', ARRAY['Camping', 'Hiking', 'Team building', 'Survival skills'], '8-16 years', 4.6, ARRAY['Accessible camping facilities', 'Medical supervision'], 'adventures@scouts.co.ke', '+254 799 901234', 'Monthly weekend trips', 'KSh 5,000/month'),
('Creative Minds Workshop', 'Eldoret - Innovation Hub', 'STEM and robotics activities designed for neurodiverse learners', ARRAY['Robotics', 'Coding', 'Engineering', 'Mathematics'], '7-14 years', 4.8, ARRAY['Sensory-friendly workspace', 'Assistive technology'], 'stem@creativeminds.co.ke', '+254 700 012345', 'Saturdays 10AM-1PM', 'KSh 3,000/month');
