-- This is a migration file. Its content should be managed by Supabase CLI.
-- It's typically a timestamped file for schema changes.
-- Example content:
-- create table public.favorites (
--   id uuid primary key default uuid_generate_v4(),
--   user_id uuid references auth.users on delete cascade,
--   item_id uuid not null,
--   item_type text not null,
--   favorited_at timestamp with time zone default now(),
--   unique (user_id, item_id, item_type)
-- );
